{% set name = "Arpeggio" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 920d12cc762edb2eb56daae64a14c93e43dc181b481c88fc79314c0df6ee639e

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - python


test:
  imports:
    - arpeggio

about:
  home: http://textx.github.io/Arpeggio
  dev_url: https://github.com/textX/Arpeggio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parser interpreter based on PEG grammars written in Python

extra:
  recipe-maintainers:
    - raivivek
